name: Compare authentication

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Run PowerShell script
        shell: pwsh
        run: |
          $headers=@{"X-IDENTITY-HEADER"=$env:IDENTITY_HEADER}
          $ProgressPreference = "SilentlyContinue"
          $response = Invoke-WebRequest -UseBasicParsing -Uri "$($env:IDENTITY_ENDPOINT)?resource=https://storage.azure.com/&api-version=2019-08-01" -Headers $headers
          $response.RawContent

      # System-assigned managed identity authentication with Azure CLI Action
      - name: Azure Login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      # User-assigned managed identity authentication with Azure CLI Action
      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true



      # Azure CLI Action only supports linux self-hosted runners for now.
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "test" > some_file.txt
            az storage blob upload -f some_file.txt -c mycontainer -n MyBlob