name: Compare authentication

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  hosted-agent:
    runs-on: ubuntu-latest

    steps:

      - name: Get MI token (inline)
        shell: pwsh
        continue-on-error: true
        run: |
          $headers=@{"X-IDENTITY-HEADER"=$env:IDENTITY_HEADER}
          $ProgressPreference = "SilentlyContinue"
          $response = Invoke-WebRequest -UseBasicParsing -Uri "$($env:IDENTITY_ENDPOINT)?resource=https://storage.azure.com/&api-version=2019-08-01" -Headers $headers
          $response.StatusCode

      - name: Get MI token (script)
        shell: pwsh
        continue-on-error: true
        run: |
          ./scripts/get-managed-identity-token.ps1

      # System-assigned managed identity authentication with Azure CLI Action
      - name: Azure Login with SMI
        uses: azure/login@v2
        continue-on-error: true
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Test credentials
        uses: azure/cli@v2
        continue-on-error: true
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      # User-assigned managed identity authentication with Azure CLI Action
      - name: Azure login with UMI
        uses: azure/login@v2
        continue-on-error: true
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Test credentials
        uses: azure/cli@v2
        continue-on-error: true
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Azure login with Service Principal
        uses: azure/login@v2
        continue-on-error: true
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Test credentials
        uses: azure/cli@v2
        continue-on-error: true
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            # echo "test" > some_file.txt
            # az storage blob upload -f some_file.txt -c mycontainer -n MyBlob